# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 06:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import tagging.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(editable=False)),
                ('modified_date', models.DateTimeField()),
                ('created_by', models.CharField(blank=True, default=b'', max_length=50, null=True)),
                ('modified_by', models.CharField(blank=True, default=b'', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text=b"Used to build the entry's URL.", max_length=255, unique_for_date=b'publication_date')),
                ('status', models.CharField(choices=[(b'draft', b'draft'), (b'hidden', b'hidden'), (b'published', b'published')], db_index=True, default=b'draft', max_length=10)),
                ('publication_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('comment_enabled', models.BooleanField(default=True)),
                ('tags', tagging.fields.TagField(blank=True, max_length=255, verbose_name=b'tags')),
                ('authors', models.ManyToManyField(blank=True, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='posts', to='categories.Category')),
            ],
            options={
                'get_latest_by': 'publication_date',
                'ordering': ['-publication_date'],
                'verbose_name_plural': 'posts',
                'verbose_name': 'post',
                'permissions': (('can_view_all', 'Can view all entries'), ('can_change_status', 'Can change status'), ('can_change_author', 'Can change author(s)')),
            },
        ),
        migrations.AlterIndexTogether(
            name='posts',
            index_together=set([('status', 'publication_date'), ('slug', 'publication_date')]),
        ),
    ]
