# Generated by Django 4.0.4 on 2022-07-02 14:26

from django.db import migrations, models
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='modified_by',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.SlugField(help_text="Used to build the entry's URL.", max_length=255, unique_for_date='publication_date'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('hidden', 'hidden'), ('published', 'published')], db_index=True, default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='posts',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255, verbose_name='tags'),
        ),
    ]
