# Generated by Django 4.0.4 on 2022-08-13 18:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0003_alter_posts_created_by_alter_posts_modified_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('done', models.BooleanField(default=False)),
                ('first_revision_date', models.DateTimeField(default=datetime.datetime(2022, 8, 14, 18, 15, 1, 411430))),
                ('second_revision_date', models.DateTimeField(default=datetime.datetime(2022, 8, 15, 18, 15, 1, 411483))),
                ('third_revision_date', models.DateTimeField(default=datetime.datetime(2022, 8, 16, 18, 15, 1, 411502))),
                ('seventh_revision_date', models.DateTimeField(default=datetime.datetime(2022, 8, 20, 18, 15, 1, 411524))),
                ('fifteenth_revision_date', models.DateTimeField(default=datetime.datetime(2022, 8, 27, 18, 15, 1, 411541))),
                ('last_revision_date', models.DateTimeField(default=datetime.datetime(2022, 9, 12, 18, 15, 1, 411557))),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.posts')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
