# Generated by Django 4.0.4 on 2022-08-15 14:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_posts_created_by_alter_posts_modified_by_and_more'),
        ('revision', '0002_alter_revise_fifteenth_revision_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revise',
            name='fifteenth_revision_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 29, 14, 26, 54, 525451)),
        ),
        migrations.AlterField(
            model_name='revise',
            name='first_revision_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 16, 14, 26, 54, 525388)),
        ),
        migrations.AlterField(
            model_name='revise',
            name='last_revision_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 14, 14, 26, 54, 525462)),
        ),
        migrations.AlterField(
            model_name='revise',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.posts'),
        ),
        migrations.AlterField(
            model_name='revise',
            name='second_revision_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 17, 14, 26, 54, 525415)),
        ),
        migrations.AlterField(
            model_name='revise',
            name='seventh_revision_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 22, 14, 26, 54, 525440)),
        ),
        migrations.AlterField(
            model_name='revise',
            name='third_revision_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 18, 14, 26, 54, 525428)),
        ),
    ]
