# Generated by Django 4.0.4 on 2022-09-01 12:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revision', '0003_alter_revise_fifteenth_revision_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revise',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        )
    ]
